# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='fator',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='valor',
        ),
    ]
