# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='imagens')),
                ('valor', models.IntegerField()),
                ('fator', models.CharField(choices=[('A', 'FATOR A'), ('B', 'FATOR B'), ('C', 'FATOR C')], max_length=1)),
            ],
        ),
    ]
